### ISSUE TITLE
Блокировка Discord (Ростелеком)

### ISSUE THREAD

**Issue by Fanya-dev** [censorliber/zapret#10]
Вчера (18.12.2024) где-то вечером резко вылетел дискорд и по прежнему не работает.

**Comment by Fanya-dev** [comment]
После апдейта заработало (1-ый метод), багодарю

**Comment by censorliber** [comment]
@Fanya-dev

**Comment by Fanya-dev** [comment]
@censorliber привет, сегодня (в ~00:00) отвалился методы обхода start_rostelecom2-3.cmd (для Discord). Включая start_discord1_rostelecom.cmd.

start_discord2.cmd пока работает.


_Именно start_discord1.cmd? Просто странно, так как эта стратегия особо не менялась._
Уже не помню, скорее всего не проверял.

**Comment by vsegdapavshiy** [comment]
@Fanya-dev привет! Как ты решил проблему с дс? У самого Ростелеком и не работает,хотелось бы узнать

**Comment by vsegdapavshiy** [comment]
@censorliber привет! Сможешь помочь с дс? Тоже Ростелеком и не пойму как сделать так чтоб он заработал…

**Comment by Fanya-dev** [comment]
Я использую метод 2 для дискорда, работал у меня сегодня

**Comment by vsegdapavshiy** [comment]
@Fanya-dev что за метод? Не очень понимаю

**Comment by Fanya-dev** [comment]
> @Fanya-dev что за метод? Не очень понимаю
> 

Обновись с гита, запусти start.bat
Выбери 2 метод для дискорда в консоле

**Comment by vsegdapavshiy** [comment]
@Fanya-dev я не очень понимаю во всем этом,можем ли мы как-то связаться? Чтоб вы мне помогли

**Comment by vsegdapavshiy** [comment]
@Fanya-dev я наверно понял о чем вы,щас попробую

**Comment by vsegdapavshiy** [comment]
Се,первый метод помог

**Comment by Fanya-dev** [comment]
@censorliber а есть варианты запуска с параметрами?
Условно start.bat -method 1
Хочу ярлык дискорда прост сделать, метод запускает дискорд, было бы удобно))
